### ISSUE TITLE
Null check operator used on a null value when using serializers.serializeWith(serializer, object)

### ISSUE THREAD

**Issue by hoc081098** [google/built_value.dart#1013]
https://github.com/google/built_value.dart/blob/c161995103bb134b21ffe4ab6ecfd71a85d390ad/built_value/lib/src/built_json_serializers.dart#L67

## Log
```
Null check operator used on a null value, #0      BuiltJsonSerializers.serialize (package:built_value/src/built_json_serializers.dart:67:51)
#1      BuiltListSerializer.serialize.<anonymous closure> (package:built_value/src/built_list_serializer.dart:28:36)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:411:31)
#3      ListIterator.moveNext (dart:_internal/iterable.dart:340:26)
#4      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
#5      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#6      new List.of (dart:core-patch/array_patch.dart:50:28)
#7      ListIterable.toList (dart:_internal/iterable.dart:211:44)
#8      BuiltJsonSerializers._serialize (package:built_value/src/built_json_serializers.dart:103:14)
#9      BuiltJsonSerializers.serialize (package:built_value/src/built_json_serializers.dart:69:18)
#10     _$MemberRes<…>
```

**Comment by davidmorgan** [comment]
Will handle this as https://github.com/google/built_value.dart/issues/1049

**Comment by davidmorgan** [comment]
Thanks! I have a PR ready, should be fixed in next release.
