### ISSUE TITLE
Deserialization fails with custom serializer for nullable field. 

### ISSUE THREAD

**Issue by radzish** [google/built_value.dart#1035]
See following example:

```dart

import 'dart:convert';

import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';
import 'package:built_value/standard_json_plugin.dart';

part 'nullable_issue.g.dart';

void main(List<String> arguments) {
  final json = '''
  {
    "booking_date": ""
  }
  ''';

  final model = serializers.deserializeWith(Model.serializer, jsonDecode(json));

  print(model);
}

abstract class Model implements Built<Model, ModelBuilder> {
  Model._();

  factory Model([Function(ModelBuilder b) updates]) = _$Model;

  static Serializer<Model> get serializer => _$modelSerializer;

  DateTime? get booking_date;
}

@SerializersFor([Model])
final Serializers serializers = (_$serializers.toBuilder()
      ..addPlugin(StandardJsonPlugin())
      ..add(DateTimeSerializer()))
    .build();

class DateTimeSerializer implements PrimitiveSerializer<DateTime?> {
  @override
  DateTime? deserialize(Serializers serializers, Object? serialized, {FullType specifiedType = FullType.unspecified}) {
    if (serialized != null && serialized is String && serialized.isNotEmpty) {
      return DateTime.parse(serialized).toLocal();
    } else {
      return null;
    }
  }

  @override
  Object serialize(Serializers serializers, DateTime? object, {FullType specifiedType = FullType.unspecified}) {
    if (object != null) {
      return object.toUtc().toIso8601String();
    } else {
      return Object();
    }
  }

  @override
  Iterable<Type> get types => [DateTime];

  @override
  String get wireName => 'DateTime';
}

```

This will fail with following error:

```
Unhandled exception:
Deserializing '[booking_date, ]' to 'Model' failed due to: type 'Null' is not a subtype of type 'DateTime' in type cast
#0      BuiltJsonSerializers._deserialize (package:built_value/src/built_json_serializers.dart:173:11)
#1      BuiltJsonSerializers.deserialize (package:built_value/src/built_json_serializers.dart:121:18)
#2      BuiltJsonSerializers.deserializeWith (package:built_value/src/built_json_serializers.dart:42:12)
#3      main (path/nullable_issue.dart:16:29)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

This happens because of incorrect type case in generated serializer code:

```dart
...
      switch (key) {
        case 'booking_date':
          result.booking_date = serializers.deserialize(value,
              specifiedType: const FullType(DateTime)) as DateTime;
          break;
      }
...
```

I think it would be correct to cast to **DateTime?**

built_value: 8.0.6
built_value_generator: 8.0.6
Dart SDK version: 2.12.2 (stable) (Wed Mar 17 10:30:20 2021 +0100) on "linux_x64"

**Comment by davidmorgan** [comment]
Will handle this as https://github.com/google/built_value.dart/issues/1049

**Comment by davidmorgan** [comment]
Thanks! I think you are correct about the cast change, sending a PR.
