### ISSUE TITLE
How to serializer Color？

### ISSUE THREAD

**Issue by T-Oner** [google/built_value.dart#1078]
```dart

abstract class CategoryVo implements Built<CategoryVo, CategoryVoBuilder> {
  CategoryVo._();

  factory CategoryVo([void Function(CategoryVoBuilder) updates]) = _$CategoryVo;

  static void _initializeBuilder(CategoryVoBuilder builder) => builder
    ..sid = newUuid()
    ..type = CategoryType.normal
    ..score = 0;

  static Serializer<CategoryVo> get serializer => _$categoryVoSerializer;

  static CategoryVo fromJson(String source) =>
      jsonSerializers.deserializeWith(serializer, json.decode(source))!;

  String toJson() {
    return jsonSerializers.toJson(serializer, this);
  }

  Color get color;

}
```

The output:

```log
E/flutter ( 7356): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Bad state: No serializer for 'Color'.
E/flutter ( 7356): #0      BuiltJsonSerializers._serialize (package:built_value/src/built_json_serializers.dart:80:9)
E/flutter ( 7356): #1      BuiltJsonSerializers.serialize (package:built_value/src/built_json_serializers.dart:69:18)
E/flutter ( 7356): #2      BuiltJsonSerializers._serialize (package:built_value/src/built_json_serializers.dart:97:16)
E/flutter ( 7356): #3      BuiltJsonSerializers.serialize (package:built_value/src/built_json_serializers.dart:69:18)
E/flutter ( 7356): #4      _$CategoryVoSerializer.serialize (package:timez/vo/category_vo.g.dart:24:19)
E/flutter ( 7356): #5      BuiltJsonSerializers._serialize (package:built_value/src/built_json_serializers.dart:103:18)
E/flutter ( 7356): #6      BuiltJsonSerializers.serialize (package:built_value/src/built_json_serializers.dart:69:18)
E/flutter ( 7356): #7      _$TaskVoSerializer.serialize (package:timez/vo/task_vo.g.dart:24:19)
E/flutter ( 7356): #8      BuiltJsonSerializers._serialize (package:built_value/src/built_json_serializers.dart:103:18)
E/flutter ( 7356): #9      BuiltJsonSerializers.serialize (package:built_value/src/built_json_serializers.dart:69:18)
E/flutter ( 7356): #10     BuiltJsonSerializers.serializeWith (package:built_value/src/built_json_serializers.dart:53:12)
E/flutter ( 7356): #11     BuiltJsonSerializers.toJson (package:built_value/src/built_json_serializers.dart:58:24)
E/flutter ( 7356): #12     TaskVo.toJson (package:timez/vo/task_vo.dart:34:28)
E/flutter ( 7356): #13     AppDataRepository.createUserGuideCategory (package:timez/repository/app_data_repository.dart:152:17)
E/flutter ( 7356): #14     _onCreateUserGuideProject.<anonymous closure> (package:timez/redux/module/data/data_middleware.dart:48:29)
E/flutter ( 7356): #15     _onCreateUserGuideProject.<anonymous closure> (package:timez/redux/module/data/data_middleware.dart:45:10)
E/flutter ( 7356): #16     TypedMiddleware.call (package:redux/src/utils.dart:229:24)
E/flutter ( 7356): #17     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #18     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #19     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #20     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #21     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #22     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #23     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #24     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #25     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #26     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #27     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #28     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #29     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #30     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #31     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #32     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #33     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #34     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #35     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #36     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #37     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #38     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #39     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #40     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #41     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #42     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #43     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #44     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #45     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #46     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #47     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #48     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #49     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #50     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #51     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #52     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #53     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #54     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #55     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #56     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #57     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #58     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #59     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #60     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #61     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #62     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #63     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #64     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #65     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #66     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #67     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #68     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #69     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #70     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #71     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #72     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #73     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #74     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #75     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #76     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #77     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #78     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #79     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #80     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #81     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #82     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #83     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #84     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #85     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #86     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #87     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #88     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #89     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #90     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #91     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #92     TypedMiddleware.call (package:redux/src/utils.dart:231:18)
E/flutter ( 7356): #93     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #94     LoggerMiddleware.call (package:timez/misc/logger/redux_logger.dart:10:9)
E/flutter ( 7356): #95     Store._createDispatchers.<anonymous closure> (package:redux/src/store.dart:255:43)
E/flutter ( 7356): #96     Store.dispatch (package:redux/src/store.dart:267:27)
E/flutter ( 7356): #97     HelpScreen.build.<anonymous closure> (package:timez/screen/settings/help/help_screen.dart:27:22)
E/flutter ( 7356): #98     _TapWidgetState.build.<anonymous closure> (package:timez/widget/tap_widget.dart:43:25)
E/flutter ( 7356): #99     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 7356): #100    TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:607:11)
E/flutter ( 7356): #101    BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
E/flutter ( 7356): #102    BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
E/flutter ( 7356): #103    PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter ( 7356): #104    PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:93:12)
E/flutter ( 7356): #105    PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:138:9)
E/flutter ( 7356): #106    _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
E/flutter ( 7356): #107    PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:136:18)
E/flutter ( 7356): #108    PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:122:7)
E/flutter ( 7356): #109    GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439:19)
E/flutter ( 7356): #110    GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419:22)
E/flutter ( 7356): #111    RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:287:11)
E/flutter ( 7356): #112    GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
E/flutter ( 7356): #113    GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
E/flutter ( 7356): #114    GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
E/flutter ( 7356): #115    GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
E/flutter ( 7356): #116    _rootRunUnary (dart:async/zone.dart:1370:13)
E/flutter ( 7356): #117    _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter ( 7356): #118    _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter ( 7356): #119    _invoke1 (dart:ui/hooks.dart:182:10)
E/flutter ( 7356): #120    PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:282:7)
E/flutter ( 7356): #121    _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
```

**Comment by davidmorgan** [comment]
You will need to supply your own serializer for `Color`, `built_value` doesn't come with one.

If you ask on stackoverflow you might find someone has created one already :)
