### ISSUE TITLE
Bad state: No serializer for '_$KeyAttribute'

### ISSUE THREAD

**Issue by DanTup** [google/built_value.dart#119]
I'm sure this is my fault, but I'm not sure how to debug it. Running build/watch doesn't show any errors but when I try to serialise I get a runtime error:

```text
Unhandled exception:
Bad state: No serializer for '_$KeyAttribute'.
#0      BuiltJsonSerializers._serialize (package:built_value/src/built_json_serializers.dart:50:9)
#1      BuiltJsonSerializers.serialize (package:built_value/src/built_json_serializers.dart:38:18)
#2      BuiltJsonSerializers._serialize (package:built_value/src/built_json_serializers.dart:68:16)
#3      BuiltJsonSerializers.serialize (package:built_value/src/built_json_serializers.dart:38:18)
#4      BuiltListSerializer.serialize.<anonymous closure> (package:built_value/src/built_list_serializer.dart:27:36)
#5      MappedListIterable.elementAt (dart:_internal/iterable.dart:416)
#6      ListIterable.toList (dart:_internal/iterable.dart:222)
#7      BuiltJsonSerializers._serialize (package:built_value/src/built_json_serializers.dart:73:14)
#8      BuiltJsonSerializers.serialize (package:built_value/src/built_json_serializers.dart:38:18)
#9      _$CreateTableRequestSerializer.serialize (package:chart_data_migrator/classes.g.dart:112:19)
#10     BuiltJsonSerializers._serialize (package:built_value/src/built_json_serializers.dart:54:42)
#11     BuiltJsonSerializers.serialize (package:built_value/src/built_json_serializers.dart:38:18)
```

I've attached the original file and generated file if it helps; I can't see anything obviously wrong with them.

[classes.dart](https://github.com/google/built_value.dart/files/769432/classes.dart.txt)
[classes.g.dart](https://github.com/google/built_value.dart/files/769433/classes.g.dart.txt)

**Comment by DanTup** [comment]
Whoops; I should've read the error (and docs) harder. I only had the static serializer declared in my top-level class!
