### ISSUE TITLE
New error with custom builder

### ISSUE THREAD

**Issue by filiph** [google/built_value.dart#175]
I have a BuiltValue class with a custom Builder. This worked fine, but since I upgraded Dart 1.23 to 1.24 (and, in the process, pkg:code_builder 1.0.2->1.0.3, pkg:code_transformers 0.5.1+2->0.5.1+3, pkg:func 0.1.1->1.0.0, among other things*), the built_value builder fails with the following error

*) those other things that upgraded seem less relevant to code builder, like pkg:async or pkg:csslib.

```
[SEVERE] runBuilder: Error running BuiltValueGenerator for abstract class Actor with EntityBehavior implements Built<Actor, ActorBuilder>.
Please make the following changes to use BuiltValue:

1. Make builder field categories have type: List<String>
2. Make builder field followingActorId have type: int
3. Make builder field hitpoints have type: int
4. Make builder field gold have type: int
5. Make builder field id have type: int
6. Make builder field initiative have type: int
7. Make builder field maxHitpoints have type: int
8. Make builder field stamina have type: int
#0      ValueSourceClass.generateCode (package:built_value_generator/src/value_source_class.dart:230:28)
#1      BuiltValueGenerator.generate (package:built_value_generator/built_value_generator.dart:21:61)
<asynchronous suspension>
#2      _processUnitMember (package:source_gen/src/builder.dart:116:35)
<asynchronous suspension>
#3      _generate (package:source_gen/src/builder.dart:107:12)
<asynchronous suspension>
#4      GeneratorBuilder._generateForLibrary (package:source_gen/src/builder.dart:51:15)
<asynchronous suspension>
#5      GeneratorBuilder.build (package:source_gen/src/builder.dart:35:11)
<asynchronous suspension>
#6      runBuilder.buildForInput (package:build/src/generate/run_builder.dart:33:21)
<asynchronous suspension>
#7      MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#8      ListIterator.moveNext (dart:_internal/iterable.dart:342)
#9      Future.wait (dart:async/future.dart:355)
#10     runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:39:31)
#11     _rootRun (dart:async/zone.dart:1120)
#12     _CustomZone.run (dart:async/zone.dart:1001)
#13     runZoned (dart:async/zone.dart:1467)
#14     scopeLog (package:build/src/builder/logging.dart:13:5)
#15     runBuilder (package:build/src/generate/run_builder.dart:39:9)
<asynchronous suspension>
#16     BuildImpl._runBuilder (package:build_runner/src/generate/build_impl.dart:552:13)
<asynchronous suspension>
#17     BuildImpl._runPhases.<anonymous closure> (package:build_runner/src/generate/build_impl.dart:442:16)
<asynchronous suspension>
#18     MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#19     ListIterator.moveNext (dart:_internal/iterable.dart:342)
#20     Future.wait (dart:async/future.dart:355)
#21     BuildImpl._runPhases (package:build_runner/src/generate/build_impl.dart:439:20)
<asynchronous suspension>
#22     logWithTime (package:build_runner/src/logging/logging.dart:19:28)
<asynchronous suspension>
#23     BuildImpl.runBuild.<anonymous closure> (package:build_runner/src/generate/build_impl.dart:146:26)
<asynchronous suspension>
#24     Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:93:24)
#25     _rootRun (dart:async/zone.dart:1120)
#26     _CustomZone.run (dart:async/zone.dart:1001)
#27     runZoned (dart:async/zone.dart:1467)
#28     Chain.capture (package:stack_trace/src/chain.dart:91:12)
#29     BuildImpl.runBuild (package:build_runner/src/generate/build_impl.dart:78:11)
<asynchronous suspension>
#30     WatchImpl.runWatch.doBuild (package:build_runner/src/generate/watch_impl.dart:160:22)
#31     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21)
#32     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:366)
#33     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:394)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

The thing is, ActorBuilder does have those fields typed exactly as the error message asks me to:

```
abstract class ActorBuilder implements Builder<Actor, ActorBuilder> {
  @virtual
  bool alreadyMentioned = true;
  @virtual
  List<String> categories = <String>[];
  @nullable
  @virtual
  Item currentWeapon;
  @nullable
  @virtual
  Item shield;
  @virtual
  Pose pose = Pose.standing;
  @virtual
  int hitpoints = 1;
  @virtual
  int gold = 0;
  @virtual
  int maxHitpoints = 1;
  @virtual
  int stamina = 0;
  @virtual
  int id;
  @virtual
  int initiative = 100;
  @virtual
  bool isActive = true;
  @virtual
  bool isPlayer = false;
  @virtual
  Set<Item> items = new Set();
  @virtual
  String name;
  @virtual
  String currentRoomName;
  @virtual
  bool nameIsProperNoun = true;
  @virtual
  Pronoun pronoun = Pronoun.IT;
  @nullable
  @virtual
  int followingActorId;
  @virtual
  Team team = playerTeam;
  @nullable
  @virtual
  CombineFunction combineFunction;

  factory ActorBuilder() = _$ActorBuilder;
  ActorBuilder._();
}
```

At this point I'll probably go with the auto-generated builder, since now I know how to do this with 'defaults'. But it would still be nice to know what went wrong.

**Comment by davidmorgan** [comment]
Hmm. Is it possible that you have a .dart_tool folder with cached data causing problems? I've noticed this a few times.

I wasn't able to reproduce the error on the end_to_end test package -- which has one example with a custom builder.

**Comment by filiph** [comment]
I found a `.dart_tool` folder. As I just confirmed, it's being rebuilt every time I run watch.dart, so I'm not sure if that was the issue or not.

I went with using the automatic builder, which fixed it. I won't go into the trouble of trying to revive this issue, so feel free to close this bug.

**Comment by davidmorgan** [comment]
Thanks.
