### ISSUE TITLE
Exception with version 4.0

### ISSUE THREAD

**Issue by zoechi** [google/built_value.dart#220]
```
 $ dart tool/build.dart
[INFO] Build: Reading cached dependency graph...
[INFO] Build: Reading cached dependency graph completed, took 14ms

[INFO] Build: Finalizing build setup...
[INFO] Build: Initializing inputs
[INFO] Build: Deleting previous outputs
[INFO] Build: Deleting 8 declared outputs which already existed on disk.
[INFO] Build: Finalizing build setup completed, took 216ms

[INFO] Build: Running build...
[SEVERE] runBuilder: Error in BuiltValueGenerator for Instance of 'LibraryReader'.
NoSuchMethodError: The method 'toStringValue' was called on null.
Receiver: null
Tried calling: toStringValue()
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)
#2      SerializerSourceField.isNullable.<anonymous closure> (package:built_value_generator/src/serializer_source_field.dart:50:49)
#3      Object&ListMixin.any (dart:collection/list.dart:115)
#4      SerializerSourceField.isNullable (package:built_value_generator/src/serializer_source_field.dart:50:8)
#5      _$SerializerSourceField.isNullable (package:built_value_generator/src/serializer_source_field.g.dart:38:49)
#6      SerializerSourceClass._generateRequiredFieldSerializers.<anonymous closure> (package:built_value_generator/src/serializer_source_class.dart:277:34)
#7      WhereIterator.moveNext (dart:_internal/iterable.dart:438)
#8      MappedIterator.moveNext (dart:_internal/iterable.dart:390)
#9      Iterable.join (dart:core/iterable.dart:316)
#10     SerializerSourceClass._generateRequiredFieldSerializers (package:built_value_generator/src/serializer_source_class.dart:282:10)
#11     SerializerSourceClass.generateSerializer (package:built_value_generator/src/serializer_source_class.dart:188:31)
#12     SerializerSourceLibrary.generateCode.<anonymous closure> (package:built_value_generator/src/serializer_source_library.dart:117:47)
#13     MappedIterator.moveNext (dart:_internal/iterable.dart:391)
#14     Iterable.join (dart:core/iterable.dart:311)
#15     SerializerSourceLibrary.generateCode (package:built_value_generator/src/serializer_source_library.dart:118:14)
#16     BuiltValueGenerator.generate (package:built_value_generator/built_value_generator.dart:28:48)
<asynchronous suspension>
#17     _generate (package:source_gen/src/builder.dart:203:35)
<asynchronous suspension>
#18     _Builder._generateForLibrary (package:source_gen/src/builder.dart:79:15)
<asynchronous suspension>
#19     _Builder.build (package:source_gen/src/builder.dart:69:11)
<asynchronous suspension>
#20     runBuilder.buildForInput (package:build/src/generate/run_builder.dart:35:21)
<asynchronous suspension>
#21     MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#22     ListIterator.moveNext (dart:_internal/iterable.dart:342)
#23     Future.wait (dart:async/future.dart:385)
#24     runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:41:31)
#25     _rootRun (dart:async/zone.dart:1120)
#26     _CustomZone.run (dart:async/zone.dart:1001)
#27     runZoned (dart:async/zone.dart:1467)
#28     scopeLog (package:build/src/builder/logging.dart:12:38)
#29     runBuilder (package:build/src/generate/run_builder.dart:41:9)
<asynchronous suspension>
#30     BuildImpl._runBuilder (package:build_runner/src/generate/build_impl.dart:426:13)
<asynchronous suspension>
#31     BuildImpl._runPhases (package:build_runner/src/generate/build_impl.dart:355:14)
<asynchronous suspension>
#32     logWithTime (package:build_runner/src/logging/logging.dart:19:28)
<asynchronous suspension>
#33     BuildImpl._safeBuild.<anonymous closure> (package:build_runner/src/generate/build_impl.dart:153:26)
<asynchronous suspension>
#34     Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:93:24)
#35     _rootRun (dart:async/zone.dart:1120)
#36     _CustomZone.run (dart:async/zone.dart:1001)
#37     runZoned (dart:async/zone.dart:1467)
#38     Chain.capture (package:stack_trace/src/chain.dart:91:12)
#39     BuildImpl._safeBuild (package:build_runner/src/generate/build_impl.dart:88:11)
#40     BuildImpl.runBuild (package:build_runner/src/generate/build_impl.dart:64:24)
<asynchronous suspension>
#41     build (package:build_runner/src/generate/build.dart:62:32)
<asynchronous suspension>
#42     main (file:///Users/zoechi/dart/customers/bwu_social/bwu_social_shared/tool/build.dart:8:9)
<asynchronous suspension>
#43     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

[INFO] Build: Running build completed, took 2652ms

[INFO] Build: Caching finalized dependency graph...
[INFO] Build: Caching finalized dependency graph completed, took 31ms

[INFO] Build: Succeeded after 2929ms with 8 outputs
```

In a new simple demo project I have these model classes

  Category,
  Comment,
  Follower,
  HashTag,
  Post,
  UserAccount,

All are generated successfully, also the serializers.

`category.g.dart` contains
```dart
// Error: NoSuchMethodError: The method 'toStringValue' was called on null.
//        Receiver: null
//        Tried calling: toStringValue()
// ignore_for_file: annotate_overrides
class _$Category extends Category {
```
The category model class is the same as the other model classes (same mixin) and these custom properties:

```
  String get name;
  String get description;
  String get imageUrl;
```

**Comment by zoechi** [comment]
With serializers generated I meant

```dart
Serializers _$serializers = (new Serializers().toBuilder()
      ..add(Category.serializer)
      ..add(Comment.serializer)
      ..add(Follower.serializer)
      ..add(HashTag.serializer)
      ..add(Post.serializer)
      ..add(SysProvenance.serializer)
      ..add(UserAccount.serializer)
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(String)]),
          () => new ListBuilder<String>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(String)]),
          () => new ListBuilder<String>()))
    .build();
```
and all other model classes also contain the serializer implementation.

**Comment by davidmorgan** [comment]
It looks like it's choking on having an annotation in the file that's not a string value underneath. I'm guessing you added `@SerializersFor`?

This is an easy fix -- need to make the call to `toStringValue` with the null-aware operator -- which I will try to get in tomorrow. In the meantime it should work to move your `@SerializersFor` declaration into another file.

Thanks for reporting!

**Comment by zoechi** [comment]
If I delete the category file, I get the same error in `Comment`

```dart
// Error: NoSuchMethodError: The method 'toStringValue' was called on null.
//        Receiver: null
//        Tried calling: toStringValue()
// ignore_for_file: annotate_overrides
```

Seems to be related to the first or last element.

**Comment by zoechi** [comment]
What do you mean by

> move your @SerializersFor declaration into another file.

```dart
@SerializersFor(const [
//  Category,
  Comment,
  Follower,
  HashTag,
  Post,
  UserAccount,
])
/// Collection of generated serializers for the built_json chat example.
Serializers serializers = _$serializers = (_$serializers.toBuilder()
```
is already in it's own file.

Do I need to ensure that this file is not "seen" by the model classes?
All related libraries import a file that exports all libraries.

**Comment by zoechi** [comment]
You are right about adding `?` - that fixes it.

**Comment by davidmorgan** [comment]
Just guessing, but my thought was that it might work okay if `@SerializersFor' is in its own file -- i.e. without any classes -- as that's what all the examples / end to end tests do. But, maybe it doesn't help.

I'll get the proper fix in tomorrow.

**Comment by davidmorgan** [comment]
Hmm. I was only able to repro by having an _invalid_ annotation on a getter:

```
  @bleh
  @nullable
  String get aString;
```

where `bleh` is not a valid symbol at all. Could that be what's happening?

I'll make the code more robust, anyway.

**Comment by zoechi** [comment]
No, that would cause an analyser warning.

**Comment by davidmorgan** [comment]
Yes, exactly. I wasn't able to trigger it any other way, though.

Are you using custom annotations on built_value fields at all? Maybe there is some other type of annotation that triggers it.

**Comment by zoechi** [comment]
No, the only thing that is a bit special is that I use a mixin (as mentioned in another discussion recently)

```dart
abstract class Category extends Object
    with EntityMixin
    implements Built<Category, CategoryBuilder>, EntityMixin {
  factory Category([dynamic updates(CategoryBuilder b)]) = _$Category;
```
```dart
/// Common interface and implementation for entity classes.
abstract class EntityMixin {
  @nullable
  String get id;

  @nullable
  SysProvenance get sysProvenance;
}
```

```dart
abstract class SysProvenance
    implements Built<SysProvenance, SysProvenanceBuilder> {
  factory SysProvenance([dynamic updates(SysProvenanceBuilder b)]) =
      _$SysProvenance;

  SysProvenance._();

  static Serializer<SysProvenance> get serializer => _$sysProvenanceSerializer;

  @nullable
  String get sysCreatedByUserId;

  @nullable
  DateTime get sysCreatedDateTime;

  @nullable
  String get sysModifiedByUserId;

  @nullable
  DateTime get sysModifiedDateTime;
}
```

but that doesn't seem to cause any issues for all other model classes.

Then I have `serializers.dart`

```dart
part 'serializers.g.dart';

@SerializersFor(const [
  Category,
  Comment,
  Follower,
  HashTag,
  Post,
  UserAccount,
])

Serializers serializers = _$serializers = (_$serializers.toBuilder()).build();

Serializers jsonSerializers = (_$serializers.toBuilder()
      ..addPlugin(new StandardJsonPlugin())
      ..addPlugin(new SerializerCustomStandardJsonPlugin()))
    .build();
```

**Comment by davidmorgan** [comment]
Okay, I'm getting somewhere :)

I don't think this was a regression in 4.0 -- I was able to reproduce with 3.0, also.

The problem is only when you both mix in and implement an interface, and only when that interface is in a different file, and only when the interface uses annotations. Then, the analyzer does not read the annotations correctly.

The bad analysis result is cached on disk. So if you build, hit an error, remove the "extends Object with" then rebuild, you still get the error until you delete the cache, `rm -rf .dart_tool`.

I will roll back the change to ignore null annotations -- it's just hiding the analyzer problem.

In the meantime, workarounds: 1) don't both mixin and implement an interface; or 2) put that interface in the same file as every class that uses it; or 3) redeclare fields from such mixins/interfaces that have annotations, i.e. write the field again with the annotation in the file where it's used.

I'll file an issue against the analyzer, I think that's where the actual problem is.

**Comment by davidmorgan** [comment]
(And, I'll look at supporting mixins properly so you don't have to both extend and implement).
