### ISSUE TITLE
Cast error when trying to deserialize object

### ISSUE THREAD

**Issue by garfieldcoked** [google/built_value.dart#416]
Java Android developer experimenting with Flutter following https://github.com/brianegan/flutter_architecture_samples/tree/master/example/built_redux and Brian's other examples. I am trying to deserialize a rest response but getting the following error:

> type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Iterable<dynamic>' in type cast where

Similar to this SO question https://stackoverflow.com/questions/44592754/json-serialization-and-deserialization-to-objects-in-flutter, and my setup is also similar but still getting the above error.

Main object
```
part 'place_list.g.dart';

abstract class PlaceList implements Built<PlaceList, PlaceListBuilder> {
  static Serializer<PlaceList> get serializer => _$placeListSerializer;

  PlaceList._();
  factory PlaceList.builder([updates(PlaceListBuilder b)]) = _$PlaceList;

  String get id;
  BuiltList<Place> get places;
}
```

Nested object
```
part 'place.g.dart';

abstract class Place implements Built<Place, PlaceBuilder> {
  static Serializer<Place> get serializer => _$placeSerializer;

  Place._();
  factory Place.builder([updates(PlaceBuilder b)]) = _$Place;

  String get id;
  String get name;
  @nullable
  double get address;
}
```

I am trying to deserialize like this:
```
final standardSerializers = (serializers.toBuilder()..addPlugin(new StandardJsonPlugin())).build();
final content = json.decode(response.body);
final results = standardSerializers.deserializeWith(PlaceList.serializer, content);
```

I have also tried deserializing using but same issue:
```
final results = serializers.deserializeWith(PlaceList.serializer, json.decode(response.body));
```

A sample json looks like this:
```
{
  id: "objectId",
  places: [
	{
	  id: "1",
	  name: "Name",
	  address: ""
	}
  ]
}
```

I can see what I am doing wrong, I tried the flutter gitter was told here my be a better place.

Thanks

**Comment by dave26199** [comment]
Could you please include the stack trace that comes with the error? That'll help me figure it out :)

Thanks!

**Comment by garfieldcoked** [comment]
@dave26199 

Error is: `Unknown type on deserialization. Need either specifiedType or discriminator field.`

and the stack trace
```
#0      StandardJsonPlugin._toListUsingDiscriminator (package:built_value/standard_json_plugin.dart:158:7)
#1      StandardJsonPlugin.beforeDeserialize (package:built_value/standard_json_plugin.dart:53:16)
#2      BuiltJsonSerializers.deserialize (package:built_value/src/built_json_serializers.dart:100:18)
#3      BuiltJsonSerializers._deserialize (package:built_value/src/built_json_serializers.dart:132:18)
#4      BuiltJsonSerializers.deserialize (package:built_value/src/built_json_serializers.dart:102:18)
#5      BuiltJsonSerializers.deserializeWith (package:built_value/src/built_json_serializers.dart:32:12)
#6      ApiClient.fetchPlaces (package:my_app/src/data/api_client.dart:50:43)<asynchronous suspension>
#7      Repository.loadPlaces (package:my_app/src/data/repository.dart:98:25)<asynchronous suspension>
#8      fetchPlaces.<anonymous closure> (package:my_app/src/domain/middleware/store_middleware.dart:137:18)
#9      MiddlewareBuilder.add.<anonymous closure> (package:built_redux/src/middleware.dart:37:14)
#10     MiddlewareBuilder.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:built_redux/src/middleware.dart:53:26)
#11     ActionDispatcher.call (package:built_redux/src/action.dart:32:29)
#12     AppState.initState (file:///.../lib/main.dart:45:19)
#13     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3743:58)
#14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
#17     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:857:16)
#18     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:828:5)
#19     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:774:17)
#20     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2214:19)
#21     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:773:13)
#22     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:662:7)
#23     runApp (package:flutter/src/widgets/binding.dart:704:7)
#24     main (file:///.../lib/main.dart:17:3)
#25     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#26     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

Debugging StandardJsonPlugin._toListUsingDiscriminator the error happened:
```
  List _toListUsingDiscriminator(Map map) {
    var type = map[discriminator];

    if (type == null) {
      throw new ArgumentError('Unknown type on deserialization. '
          'Need either specifiedType or discriminator field.');
    }
```
Where discriminator = `$`

I will have a closer look at the json standard plugin and the use of discriminator.

**Comment by garfieldcoked** [comment]
For days I looked at this error, tried different solutions and just couldnt seem to catch a break. I finally saw my error today.

In `place` model, the `address` was incorrectly typed as double when it should have been string. I will update and close issue if resolved.

**Comment by garfieldcoked** [comment]
That was my issue, cant believe I missed that :(. Sorry for the noise, closing issue

**Comment by davidmorgan** [comment]
Doh. I didn't spot it either :)

FWIW, there is already an issue to improve error messages when deserialization fails:

https://github.com/google/built_value.dart/issues/408

I'll bump the priority of that.

Thanks!
