### ISSUE TITLE
Generator can't find anything to process "[SEVERE] Nothing can be built, yet a build was requested."

### ISSUE THREAD

**Issue by tobytraylor** [google/built_value.dart#524]
Originally opened this defect against built_redux but after eliminating built_redux from the built I've found that the issue is that built_value_generator can't find anything to generate.  

`SEVERE] Nothing can be built, yet a build was requested.`

This is after updating my libraries from built value 5.5.5 to the new 6.1.4 after being forced to because i made the mistake of updating flutter (and there is no going back).  All files generated fine before this.  Also, if i add built_redux back in then it's portion of the generator works fine (actions.dart).

**Comment by tobytraylor** [comment]
```dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  meta: ^1.0.4
  fluro: ^1.3.5
  #flutter_built_redux: ^0.6.0
  #built_redux: 7.5.0
  #built_redux_rx: ^0.1.2
  built_collection: '>=2.0.0 <5.0.0'
  built_value: ^6.1.4
  intl: any
  intl_translation: any
  path_provider: ^0.4.1
  cloud_firestore: ^0.8.1
  cloud_functions: ^0.0.4
  firebase_auth: ^0.6.2
  firebase_dynamic_links: ^0.1.0
  google_sign_in: ^3.2.1
  rxdart: ^0.19.0
  #validator: any
  ulid: ^1.0.1



dev_dependencies:
  #flutter_test:
  #  sdk: flutter
  #flutter_driver:
  #  sdk: flutter
  built_value_generator: ^6.1.4
  build_runner: '>=0.9.0 <0.11.0'
  test: ^1.0.0
  quiver: '>=0.21.0 <3.0.0'


dependency_overrides:
  rxdart: ^0.19.0
```

**Comment by davidmorgan** [comment]
I've just released v6.1.5 which bumps versions of the analyzer and build packages--please see if this helps.

**Comment by tobytraylor** [comment]
```[SEVERE] Build:
Nothing can be built, yet a build was requested.
pub finished with exit code 78

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      pubInteractively (package:flutter_tools/src/dart/pub.dart:186:5)
<asynchronous suspension>
#2      PackagesPassthroughCommand.runCommand
(package:flutter_tools/src/commands/packages.dart:148:11)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:383:18)
#4      _asyncThenWrapperHelper.<anonymous closure>
(dart:async/runtime/libasync_patch.dart:77:64)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#8      Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:642:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#10     Future._complete (dart:async/future_impl.dart:476:7)
#11     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#12     _AsyncAwaitCompleter.complete.<anonymous closure>
(dart:async/runtime/libasync_patch.dart:33:20)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#18     _runPendingImmediateCallback
(dart:isolate/runtime/libisolate_patch.dart:115:13)
#19     _RawReceivePortImpl._handleMessage
(dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by davidmorgan** [comment]
Try updating your `build_runner` dependency to `1.0.0`.

**Comment by tobytraylor** [comment]
Build runner updated to `1.0.0` there is no stack trace but it still emits `pub finished with exit code 78`

**Comment by davidmorgan** [comment]
You could try clearing `package:build` tmp files: you can just delete `.dart_tool/build` completely.

If it's still not working we'll probably need help from `package:build` authors to debug.

Is there any way you could get a list of which library versions you're actually using? e.g. the output of `pub upgrade`, not sure if there is a different one for flutter...

**Comment by tobytraylor** [comment]
```
  analyzer 0.33.1
  analyzer_plugin 0.0.1-alpha.5
  args 1.5.0
  async 2.0.8
  boolean_selector 1.0.4
  build 1.0.1
  build_config 0.3.1+4
  build_resolvers 0.2.2+6
  build_runner 1.0.0
  build_runner_core 1.0.2
> built_collection 4.0.0 (was 3.1.3)
  built_value 6.1.5
  built_value_generator 6.1.5
  charcode 1.1.2
  cloud_firestore 0.8.2+1
  cloud_functions 0.0.4+1
  code_builder 3.1.3
  collection 1.14.11
  convert 2.0.2
  crypto 2.0.6
  csslib 0.14.6
  dart_style 1.2.0
  firebase_auth 0.6.2+1
  firebase_core 0.2.5+1
  firebase_dynamic_links 0.1.0+1
  fixnum 0.10.8
  fluro 1.3.7
  flutter 0.0.0 from sdk flutter
  flutter_localizations 0.0.0 from sdk flutter
  front_end 0.1.6+1
  glob 1.1.7
  google_sign_in 3.2.2
  graphs 0.1.2+1
  html 0.13.3+3
  http 0.12.0
  http_multi_server 2.0.5
  http_parser 3.1.3
  intl 0.15.7
  intl_translation 0.17.2
  io 0.3.3
  js 0.6.1+1
> json_annotation 2.0.0 (was 1.2.0)
  json_rpc_2 2.0.9
  kernel 0.3.6+1
  logging 0.11.3+2
  matcher 0.12.3+1 (0.12.4 available)
  meta 1.1.6
  mime 0.9.6+2
  multi_server_socket 1.0.2
  node_preamble 1.4.4
  package_config 1.0.5
  package_resolver 1.0.6
  path 1.6.2
  path_provider 0.4.1
  pedantic 1.3.0
> petitparser 2.0.2 (was 1.7.7)
  plugin 0.2.0+3
  pool 1.3.6
  pub_semver 1.4.2
  pubspec_parse 0.1.2+3
  quiver 2.0.1
! rxdart 0.19.0 (overridden)
  shelf 0.7.3+3
  shelf_packages_handler 1.0.4
  shelf_static 0.2.8
  shelf_web_socket 0.2.2+4
  sky_engine 0.0.99 from sdk flutter
  source_gen 0.9.1+3
  source_map_stack_trace 1.1.5
  source_maps 0.10.8
  source_span 1.4.1
  stack_trace 1.9.3
  stream_channel 1.6.8
  stream_transform 0.0.14+1
  string_scanner 1.0.4
  term_glyph 1.0.1
  test 1.3.4
  timing 0.1.1+1
  typed_data 1.1.6
  ulid 1.0.1
  utf 0.9.0+5
  vector_math 2.0.8
  vm_service_client 0.2.6
  watcher 0.9.7+10
  web_socket_channel 1.0.9
  yaml 2.1.15
Warning: You are using these overridden dependencies:
! rxdart 0.19.0
Downloading json_annotation 2.0.0...
Changed 3 dependencies!
Precompiling executables...
Precompiled intl_translation:extract_to_arb.
Precompiled intl_translation:rewrite_intl_messages.
Precompiled intl_translation:make_examples_const.
Precompiled intl_translation:generate_from_arb.
Precompiled build_runner:graph_inspector.
Precompiled test:test.
Precompiled build_runner:build_runner.
```

after removing .dart_tool and doing a flutter clean i still get the exit code error.

**Comment by davidmorgan** [comment]
I'm out of ideas--would you mind asking for help over at https://github.com/dart-lang/build/issues ? Thanks.

**Comment by tobytraylor** [comment]
Found it.  The sample that i started with has a build.yaml in the root dir which apparently overrides the other one.  I've opened an issue with Brian Egan so he knows it breaks the newer code.

**Comment by tobytraylor** [comment]
The fix for this, for anybody else that started with Brian Egan's built_redux example (https://github.com/brianegan/flutter_architecture_samples/tree/master/example/built_redux), is to remove the build.yaml file from the project root dir.

**Comment by davidmorgan** [comment]
Glad you figured it out--thanks for updating!
