### ISSUE TITLE
JSON troubles

### ISSUE THREAD

**Issue by SJente** [google/built_value.dart#601]
Hey David,

Thanks for helping out this morning, i have ran in another problem and i'm not sure if i should post it here but you probably know best how to handle it.

**This is my relations.dart:**
```
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';
import 'package:built_collection/built_collection.dart';

part 'relations.g.dart';

abstract class GetRelation implements Built<GetRelation, GetRelationBuilder> {
  static Serializer<GetRelation> get serializer => _$getRelationSerializer;

  /// This id can never be null
  int get id;

  @nullable
  @BuiltValueField(wireName: 'relation_name')
  String get name;

  @nullable
  @BuiltValueField(wireName: 'relation_type')
  String get type;

  @nullable
  @BuiltValueField(wireName: 'relation_description')
  String get description;

  @nullable
  BuiltList<GetContacts> get contacts;

  @nullable
  BuiltList<GetLocations> get locations;

  GetRelation._();
  factory GetRelation([updates(GetRelationBuilder b)]) = _$GetRelation;
}

abstract class GetContacts implements Built<GetContacts, GetContactsBuilder> {
  static Serializer<GetContacts> get serializer => _$getContactsSerializer;

  @nullable
  @BuiltValueField(wireName: 'contact_id')
  int get id;

  @nullable
  @BuiltValueField(wireName: 'contact_relation_id')
  int get relation_id;

  @nullable
  @BuiltValueField(wireName: 'contact_name')
  String get name;

  @nullable
  @BuiltValueField(wireName: 'contact_phonenumber')
  String get phonenumber;

  @nullable
  @BuiltValueField(wireName: 'contact_mobile')
  String get mobile;

  @nullable
  @BuiltValueField(wireName: 'contact_email')
  String get email;

  @nullable
  @BuiltValueField(wireName: 'contact_description')
  String get description;

  @BuiltValueField(wireName: 'contact_location_id')
  int get location;

  GetContacts._();
  factory GetContacts([updates(GetContactsBuilder b)]) = _$GetContacts;
}

abstract class GetLocations implements Built<GetLocations, GetLocationsBuilder> {
  static Serializer<GetLocations> get serializer => _$getLocationsSerializer;

  @nullable
  @BuiltValueField(wireName: 'location_id')
  int get id;

  @nullable
  @BuiltValueField(wireName: 'location_relation_id')
  int get relation_id;

  @nullable
  @BuiltValueField(wireName: 'location_primary_loc')
  String get name;

  @nullable
  @BuiltValueField(wireName: 'location_name')
  bool get primary_loc;

  @nullable
  @BuiltValueField(wireName: 'location_address')
  String get address;

  @nullable
  @BuiltValueField(wireName: 'location_zipcode')
  String get zipcode;

  @nullable
  @BuiltValueField(wireName: 'location_city')
  String get city;

  @nullable
  @BuiltValueField(wireName: 'location_country')
  String get country;

  @nullable
  @BuiltValueField(wireName: 'location_phonenumber')
  String get phonenumber;

  @nullable
  @BuiltValueField(wireName: 'location_email')
  String get email;

  @nullable
  @BuiltValueField(wireName: 'location_website')
  String get website;

  @nullable
  @BuiltValueField(wireName: 'location_description')
  String get description;


  GetLocations._();
  factory GetLocations([updates(GetLocationsBuilder b)]) = _$GetLocations;
}
```

The code below here is not right i think. I need the whole output of my relation and there can be multiple contacts and locations inside.
**This is my relation_scoped_model.dart:**

```
import 'dart:convert';
import 'package:blackboks/models/relations.dart';
import 'package:scoped_model/scoped_model.dart';
import 'package:blackboks/models/serializers.dart';
import 'package:http/http.dart' as http;

class RelationScopedModel extends Model{
  List<GetContacts> _contacts = [];
  List<GetContacts> get contacts => _contacts;

  bool _isLoading = false;
  bool get isLoading => _isLoading;

  Future<dynamic> getData() async{

    String uri = "API URL";

    var res = await http.get(Uri.encodeFull(uri));
    return json.decode(res.body);
  }

  Future getRelations() async{
    _isLoading = true;
    notifyListeners();
    var responseData = await getData();

      GetRelation getRelation = serializers.deserializeWith(GetRelation.serializer, responseData);

      _contacts = getRelation.contacts.map((getLocations) => getLocations).toList();
  }
}
```

**This is how my JSON looks like:**

```
[
{
"id":,
"name":"",
"type":"",
"description":"",
"contacts":[
{
"id":,
"relation_id":,
"name":"",
"phonenumber":"",
"mobile":"",
"email":"",
"description":"",
"location":
}
],
"locations":[
{
"id":,
"relation_id":,
"primary_loc":,
"name":"",
"address":"",
"zipcode":"",
"city":"",
"country":"",
"phonenumber":"",
"email":"",
"invoice_email":,
"website":"",
"description":""
}
]
},
{
"id":,
"name":"",
"type":"",
"description":"",
"contacts":[
{
"id":,
"relation_id":,
"name":"",
"phonenumber":"",
"mobile":"",
"email":"",
"description":"",
"location":
}
],
"locations":[
{
"id":,
"relation_id":,
"primary_loc":,
"name":"",
"address":"",
"zipcode":"",
"city":"",
"country":"",
"phonenumber":"",
"email":"",
"invoice_email":"",
"website":"",
"description":""
}
]
}
]
```

**Comment by SJente** [comment]
Still no idea how to do this, you got an idea @davidmorgan ?

**Comment by davidmorgan** [comment]
Sorry--it's not clear to me what the problem is?

**Comment by SJente** [comment]
My Json starts with [{ without something like "response": [{

How do i start in my relations.dart and receive it in my scoped model?

**Comment by davidmorgan** [comment]
The JSON format you have is not directly compatible with `built_value`--you'll need to do some processing on it first, e.g. split up into individual items that correspond to the classes you've created.

**Comment by SJente** [comment]
Maybe it would be better to change the json in my rest api. How would my JSON have to look like to make it work for built_value?

**Comment by davidmorgan** [comment]
Actually on second look I think it's okay. What you need to do is just split up the list you receive and deserialize every item as a `GetRelation`.

e.g.

```
  var result = responseData.map((data) => serializers.deserializeWith(GetRelation.serializer, data)).toList();
```

**Comment by SJente** [comment]
So this is how my scoped model should look like? Because i'm still getting errors!

```
class RelationScopedModel extends Model{
  List<GetRelation> _relation = [];
  List<GetRelation> get relation => _relation;

  bool _isLoading = false;
  bool get isLoading => _isLoading;

  Future<dynamic> getData() async{

    String uri = "API url";

    var res = await http.get(Uri.encodeFull(uri));
    return json.decode(res.body);
  }

  Future getRelations() async{
    _isLoading = true;
    notifyListeners();
    var responseData = await getData();

    var result = responseData.map((data) => serializers.deserializeWith(GetRelation.serializer, data)).toList();
    
      _relation = result.relation.map((getRelations) => getRelations).toList();
  }
}
```

**Comment by davidmorgan** [comment]
`result` should end up as a `List` of `GetRelation`. You can then put that in `_relation`, rather than taking it from `result.relation`.

**Comment by SJente** [comment]
Thanks, i found out myself after it. But i'm still not sure how to get the contacts and the location in the relation. Is it just the exact same code?

**Comment by SJente** [comment]
`Text( "${widget.relation?.locations[0]?.name ?? ""}"), `
I have contacts and locations in the relation. My Text above works fine when there actually are locations or contacts.

But when there isn't a location or contacts.

`Another exception was thrown: NoSuchMethodError: The method '[]' was called on null.`

This is the full stacktrace:

```
I/flutter (22784): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (22784): The following NoSuchMethodError was thrown building
I/flutter (22784): ScopedModelDescendant<RelationScopedModel>(dirty, dependencies:
I/flutter (22784): [_InheritedModel<RelationScopedModel>]):
I/flutter (22784): The method '[]' was called on null.
I/flutter (22784): Receiver: null
I/flutter (22784): Tried calling: [](0)
I/flutter (22784): 
I/flutter (22784): When the exception was thrown, this was the stack:
I/flutter (22784): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
I/flutter (22784): #1      DetailScreenState.build.<anonymous closure> (package:blackboks/views/relations/detail_screen.dart:117:48)
I/flutter (22784): #2      ScopedModelDescendant.build (package:scoped_model/scoped_model.dart:297:12)
I/flutter (22784): #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:3789:28)
I/flutter (22784): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3736:15)
I/flutter (22784): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (22784): #6      StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (22784): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (22784): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (22784): #10     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (22784): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (22784): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (22784): #14     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (22784): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #16     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
I/flutter (22784): #17     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
I/flutter (22784): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (22784): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (22784): #21     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (22784): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (22784): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (22784): #25     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (22784): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (22784): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (22784): #29     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (22784): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #31     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (22784): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (22784): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (22784): #35     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (22784): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #37     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (22784): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (22784): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (22784): #41     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (22784): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (22784): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (22784): #45     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (22784): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (22784): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (22784): #49     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (22784): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (22784): #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (22784): #53     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (22784): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (22784): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (22784): #57     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (22784): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (22784): #60     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (22784): #61     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (22784): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (22784): #64     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (22784): #65     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (22784): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #67     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (22784): #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (22784): #70     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (22784): #71     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (22784): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #73     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (22784): #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #75     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (22784): #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #77     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (22784): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #79     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (22784): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (22784): #82     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (22784): #83     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (22784): #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (22784): #86     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (22784): #87     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (22784): #88     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (22784): #90     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (22784): #91     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (22784): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #93     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (22784): #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (22784): #96     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (22784): #97     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (22784): #98     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #99     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (22784): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (22784): #102    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (22784): #103    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (22784): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (22784): #106    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (22784): #107    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (22784): #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #109    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (22784): #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (22784): #112    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (22784): #113    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (22784): #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (22784): #115    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (22784): #116    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (22784): #117    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
I/flutter (22784): #118    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter (22784): #119    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
I/flutter (22784): #120    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
I/flutter (22784): #121    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
I/flutter (22784): #122    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:749:7)
I/flutter (22784): #124    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (22784): #125    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (22784): #126    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter (22784): (elided one frame from package dart:async)
I/flutter (22784): ════════════════════════════════════════════════════════════════════════════════════════════════════
```
