### ISSUE TITLE
Unable to deserialise objects array in json

### ISSUE THREAD

**Issue by neerajyadav** [google/built_value.dart#846]
Hi, I'm receiving error while deserialising object `array`. Any help is much appreciated.  
  
I'm receiving an array of objects in `chapters` key of json. The `json` is converted into `Map<String, dynamic>` by `Dio` http library. When deserialising the `Map`, I'm receiving following error.
``` log
 (Invalid argument(s): Unknown type on deserialization. Need either specifiedType or discriminator field.)
_hasValue:false
_stackTrace:#0      StandardJsonPlugin._toListUsingDiscriminator (package:built_value/standard_json_plugin.dart:163:7)
#1      StandardJsonPlugin.beforeDeserialize (package:built_value/standard_json_plugin.dart:58:16)
#2      BuiltJsonSerializers.deserialize (package:built_value/src/built_json_serializers.dart:103:18)
#3      BuiltJsonSerializers._deserialize (package:built_value/src/built_json_serializers.dart:143:18)
#4      BuiltJsonSerializers.deserialize (package:built_value/src/built_json_serializers.dart:105:18)
#5      BuiltJsonSerializers.deserializeWith (package:built_value/src/built_json_serializers.dart:36:12)
#6      LearnLevelModel.fromMap (package:LearnApp/src/models/learn_level_model.dart:50:23)
```   
Json structure: 
``` json
{
  "level": {
    "id": 1,
    "name": "Elementary",
    "introduction": "A quick introduction...",
    "sequence": 1,
    "points": 0,
    "percentageCompleted": 0,
    "status": "started"
  },
  "chapters": [{
      "id": 3,
      "levelId": 1,
      "name": "Chapter 3",
      "title": "Rules of the game",
      "duration": 9,
      "sequence": 3,
      "points": 10,
      "percentageCompleted": 0,
      "status": "started"
    },
    {
      "id": 2,
      "levelId": 1,
      "name": "Chapter 2",
      "title": "Rankings",
      "duration": 4,
      "sequence": 2,
      "points": 10,
      "percentageCompleted": 0,
      "status": "started"
    }]
}
```
**  `learn_level_model.dart` **
``` dart
abstract class LearnLevelModel
    implements Built<LearnLevelModel, LearnLevelModelBuilder> {
  LearnLevelModel._();

  factory LearnLevelModel([updates(LearnLevelModelBuilder b)]) =
      _$LearnLevelModel;

  @BuiltValueField(wireName: 'chapters', serialize: true)
  BuiltList<ChapterMetadata> get chapters;

  @BuiltValueField(wireName: 'level')
  LearnLevel get level;

  static LearnLevelModel fromMap(Map<String, dynamic> data) {  // Exception is raised here.
    if (data == null) return null;
    return serializers.deserializeWith(LearnLevelModel.serializer, data);
  }

  Map<String, dynamic> toMap() {
    return serializers.serializeWith(LearnLevelModel.serializer, this) as Map;
  }

  static Serializer<LearnLevelModel> get serializer =>
      _$learnLevelModelSerializer;
}
```
** `learn_level.dart` **
``` dart
abstract class LearnLevel implements Built<LearnLevel, LearnLevelBuilder> {
  LearnLevel._();

  factory LearnLevel([updates(LearnLevelBuilder b)]) = _$LearnLevel;

  @BuiltValueField(wireName: 'status')
  String get status;
  @BuiltValueField(wireName: 'percentageCompleted')
  int get percentageCompleted;
  @BuiltValueField(wireName: 'id')
  int get id;
  @BuiltValueField(wireName: 'name')
  String get name;
  @BuiltValueField(wireName: 'introduction')
  String get introduction;
  @BuiltValueField(wireName: 'sequence')
  int get sequence;
  @BuiltValueField(wireName: 'points')
  int get points;

  static LearnLevel fromMap(Map<String, dynamic> data) {
    if (data == null) return null;
    return serializers.deserializeWith(LearnLevel.serializer, data);
  }

  Map<String, dynamic> toMap() {
    return serializers.serializeWith(LearnLevel.serializer, this) as Map;
  }

  static Serializer<LearnLevel> get serializer => _$learnLevelSerializer;
}
```
** `chapter_metadata.dart` **
```  dart
abstract class ChapterMetadata
    implements Built<ChapterMetadata, ChapterMetadataBuilder> {
  ChapterMetadata._();

  factory ChapterMetadata([updates(ChapterMetadataBuilder b)]) =
      _$ChapterMetadata;

  @BuiltValueField(wireName: 'status')
  String get status;
  
  @nullable
  @BuiltValueField(wireName: 'percentageCompleted')
  int get percentageCompleted;
  
  @nullable
  @BuiltValueField(wireName: 'quizScore')
  int get quizScore;
  
  @nullable
  @BuiltValueField(wireName: 'totalQuestions')
  int get totalQuestions;
  @BuiltValueField(wireName: 'id')
  int get id;
  @BuiltValueField(wireName: 'levelId')
  int get levelId;

  @nullable
  @BuiltValueField(wireName: 'name')
  String get name;
  @BuiltValueField(wireName: 'title')
  String get title;
  @BuiltValueField(wireName: 'duration')
  int get duration;
  @BuiltValueField(wireName: 'sequence')
  int get sequence;
  
  @nullable
  @BuiltValueField(wireName: 'points')
  int get points;

  static ChapterMetadata fromMap(Map<String, dynamic> data) {
    if (data == null) return null;
    return serializers.deserializeWith(ChapterMetadata.serializer, data);
  }

  Map<String, dynamic> toMap() {
    return serializers.serializeWith(ChapterMetadata.serializer, this) as Map;
  }

  static Serializer<ChapterMetadata> get serializer =>
      _$chapterMetadataSerializer;
}
```

**Comment by neerajyadav** [comment]
Solved. I think the code generated by build_runner was not in sync with built value model files. `Model` entry was missing from list of `serializers` registered.
