### ISSUE TITLE
Deserializing failed, failed due to: Bad state: No builder factory for BuiltList<BuiltVendorService>

### ISSUE THREAD

**Issue by kirkcharlesniv** [google/built_value.dart#982]
`BuiltVendorService` is at the `@SerializersFor` annotation, and has entry on the `serializers.g.dart`
```
@SerializersFor(const [
  ...
  BuiltVendorService,
  ...
])
```
```
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(BuiltVendorService)]),
          () => new ListBuilder<BuiltVendorService>()))
```

I also ran `flutter pub run build_runner watch --delete-conflicting-outputs` to no avail of fixing the issue.

**Comment by kirkcharlesniv** [comment]
```
[log] Deserializing '[data, [{vendor_id: 1, vendor_name: sample burial, industry_id: 1, date_creat...' to 'BuiltVendor' failed due to: Deserializing '[{vendor_id: 1, vendor_name: sample burial, industry_id: 1, date_created: 202...' to 'BuiltList<BuiltVendorData>' failed due to: Deserializing '[vendor_id, 1, vendor_name, sample burial, industry_id, 1, date_created, 2021...' to 'BuiltVendorData' failed due to: Deserializing '[{vendor_service_id: 6, service_id: 1, vendor_id: 1, service: {service_id: 1,...' to 'BuiltList<BuiltVendorService>' failed due to: Bad state: No builder factory for BuiltList<BuiltVendorService>. Fix by adding one, see SerializersBuilder.addBuilderFactory.
[log] #0      BuiltJsonSerializers._deserialize
package:built_value/src/built_json_serializers.dart:154
#1      BuiltJsonSerializers.deserialize
package:built_value/src/built_json_serializers.dart:105
#2      BuiltJsonSerializers.deserializeWith
package:built_value/src/built_json_serializers.dart:36
#3      BuiltVendor.fromJson
package:mobile/…/built/built_vendor.dart:29
#4      HomeBloc.mapEventToState
package:mobile/…/bloc/home_bloc.dart:38
      <asynchronous suspension>
#5      Bloc._bindEventsToStates.<anonymous closure>
package:bloc/src/bloc.dart:231
#6      Stream.asyncExpand.<anonymous closure>.<anonymous closure> (dart:async/stream.dart:644:30)
#7      _rootRunUnary (dart:async/zone.dart:1198:47)
#8      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#11     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
#12     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
#13     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
#14     _rootRun (dart:async/zone.dart:1182:47)
#15     _CustomZone.run (dart:async/zone.dart:1093:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#18     _rootRun (dart:async/zone.dart:1190:13)
#19     _CustomZone.run (dart:async/zone.dart:1093:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

Here's the error and the stack trace.

**Comment by kirkcharlesniv** [comment]
Tried to recreate `BuiltVendorService` but with different name seems to work, that's weird. Anyways, if you have any questions let me know, thanks.
